In [1]:
from huggingface_hub import login

login(token="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")

In [2]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("CiferAI/Cifer-Fraud-Detection-Dataset-AF")
print(ds)

DatasetDict({
    train: Dataset({
        features: ['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud', 'isFlaggedFraud'],
        num_rows: 21000000
    })
})

In [3]:
import pandas as pd

column_names = [
    'step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg',
    'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest',
    'isFraud', 'isFlaggedFraud'
]

df = ds["train"].to_pandas()[column_names]
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,371,CASH_OUT,367336.05,sdv-pii-r8zd6,4514816.83,2108392.86,sdv-pii-q6998,1265486.06,2454140.46,0,0
1,368,TRANSFER,238.63,sdv-pii-xq6z3,430944.71,1865444.60,sdv-pii-n2ql8,107927.46,2021.16,0,0
2,141,CASH_OUT,254.93,sdv-pii-805w0,839593.53,8008353.88,sdv-pii-yo0z6,773352.22,20.79,0,0
3,191,CASH_IN,501547.39,sdv-pii-279tw,41226.40,28633.52,sdv-pii-9zlyl,6825363.55,16442078.24,0,0
4,169,TRANSFER,71832.00,sdv-pii-ksz58,248694.60,793617.86,sdv-pii-0ykbo,579313.76,829850.96,0,0
...,...,...,...,...,...,...,...,...,...,...,...
20999995,198,CASH_OUT,13315.94,C639852412,2423268.89,12413862.98,M1385592393,1504614.61,0.10,0,0
20999996,198,CASH_IN,44194.38,C1479656058,815049.21,4148521.18,M2086295095,183371.08,0.00,0,0
20999997,122,PAYMENT,79701.00,C1817049050,0.08,11665.50,C1033381601,769833.04,0.08,0,0
20999998,139,TRANSFER,473635.45,C532984095,1759699.35,153806.01,C1680845012,641670.03,108828.76,0,0
20999999,361,TRANSFER,46818.99,C1533425594,2550013.30,2696965.11,C788621192,140915.79,0.00,0,0

Important thing to note: Dataset is an Homogeneous Graph
Below are the nodes for GNN
Nodes (account): nameOrig and nameDest.
Edges (transaction): transaction between the accounts - meaning the transaction between nameOrig and nameDest.
Edge Features (transaction details - describes the interaction between two nodes): step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest.
Lables: isFraud and isFlaggedFraud.

In [4]:
nodes = pd.unique(df[["nameOrig", "nameDest"]].values.ravel())
print(nodes[:10])
node_to_id = {node: i for i, node in enumerate(nodes)}

['sdv-pii-r8zd6' 'sdv-pii-q6998' 'sdv-pii-xq6z3' 'sdv-pii-n2ql8'
 'sdv-pii-805w0' 'sdv-pii-yo0z6' 'sdv-pii-279tw' 'sdv-pii-9zlyl'
 'sdv-pii-ksz58' 'sdv-pii-0ykbo']

In [5]:
edge_index = df[["nameOrig", "nameDest"]].applymap(node_to_id.get).values.T
print(edge_index[:, :10])

C:\Users\abeke\AppData\Local\Temp\ipykernel_42784\671472065.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  edge_index = df[["nameOrig", "nameDest"]].applymap(node_to_id.get).values.T

[[ 0  2  4  6  8 10 12 14 16 18]
 [ 1  3  5  7  9 11 13 15 17 19]]

In [6]:
edges = df[["nameOrig", "nameDest"]]
edges.head(10)

        nameOrig       nameDest
0  sdv-pii-r8zd6  sdv-pii-q6998
1  sdv-pii-xq6z3  sdv-pii-n2ql8
2  sdv-pii-805w0  sdv-pii-yo0z6
3  sdv-pii-279tw  sdv-pii-9zlyl
4  sdv-pii-ksz58  sdv-pii-0ykbo
5  sdv-pii-mra6t  sdv-pii-1qflq
6  sdv-pii-fo5mx  sdv-pii-y82ro
7  sdv-pii-m41h5  sdv-pii-7zz12
8  sdv-pii-9lkn2  sdv-pii-uho1q
9  sdv-pii-kev1b  sdv-pii-bnluu

In [7]:
edges_features = df[[
    "step", "type", "amount",
    "oldbalanceOrg", "newbalanceOrig",
    "oldbalanceDest", "newbalanceDest"
]]
edges_features.head(10)

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest
0,371,CASH_OUT,367336.05,4514816.83,2108392.86,1265486.06,2454140.46
1,368,TRANSFER,238.63,430944.71,1865444.60,107927.46,2021.16
2,141,CASH_OUT,254.93,839593.53,8008353.88,773352.22,20.79
3,191,CASH_IN,501547.39,41226.40,28633.52,6825363.55,16442078.24
4,169,TRANSFER,71832.00,248694.60,793617.86,579313.76,829850.96
5,374,PAYMENT,172354.76,176829.98,35107.31,299504.68,282.50
6,257,CASH_IN,604830.32,409383.76,179779.01,7676540.43,43961414.19
7,428,CASH_IN,230293.41,98878.25,1932878.65,3702375.89,6138290.86
8,436,CASH_IN,5038.30,862919.64,13275102.80,4691791.26,5418837.86
9,232,CASH_OUT,35508.34,2071693.88,1209503.24,1437966.25,2315515.52

In [8]:
labels = df[[
    'isFraud', 'isFlaggedFraud'
]]
labels.head(10)

   isFraud  isFlaggedFraud
0        0               0
1        0               0
2        0               0
3        0               0
4        0               0
5        0               0
6        0               0
7        0               0
8        0               0
9        0               0